"""add seating allocation tables

Revision ID: 4ddf24b3503c
Revises: 32365d4fbdae
Create Date: 2026-09-19 10:11:59.233134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddf24b3503c'
down_revision = '32365d4fbdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id')
    )
    op.create_table('invigilator_duties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'faculty_id', name='uq_exam_faculty_invigilator'),
    sa.UniqueConstraint('examination_id', 'room_id', name='uq_exam_room_invigilator')
    )
    op.create_table('seat_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_run_id', sa.Integer(), nullable=False),
    sa.Column('examination_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('manually_adjusted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_run_id'], ['allocation_runs.id'], ),
    sa.ForeignKeyConstraint(['examination_id'], ['examinations.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examination_id', 'seat_id', name='uq_exam_seat_allocation'),
    sa.UniqueConstraint('examination_id', 'student_id', name='uq_exam_student_allocation')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seat_allocations')
    op.drop_table('invigilator_duties')
    op.drop_table('allocation_runs')
    # ### end Alembic commands ###
