"""Add room table

Revision ID: a96e03d61b7f
Revises: 3e96bae78896
Create Date: 2026-09-17 17:39:48.274829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a96e03d61b7f'
down_revision = '3e96bae78896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=50), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('columns', sa.Integer(), nullable=False),
    sa.Column('students_per_desk', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    # ### end Alembic commands ###
